# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Blog
email: your-email@jekyll-blog.com
description: > # this means to ignore newlines until "baseurl:"
  New blog site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
gems: [jekyll-paginate]
# Build settings
paginate: 3
#paginate_path: "/page:num/"
markdown: kramdown 
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
